name: Create PR on Push

on:
  push:
    branches: [main]

jobs:
  create-pr:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update from fork
          title: Update from fork
          body: This PR was automatically created from a push to the main branch of your fork.
          labels: automation
          head: Annany2002:main
          base: akshatmishra25:main
